dividends/urls.py
from django.urls import path
from . import views


app_name = 'dividends'

urlpatterns = [

    path('list-disbursements/', views.ListDisbursements.as_view(), name='list-disbursements'),
    path('create-issue/', views.CreateDividendIssue.as_view(), name='create-issue'),
    path('list-issues/', views.ListDividendIssues.as_view(), name='list-issues'),
    path('calculate-dividends/', views.CalculateDividends.as_view(), name='calculate-dividends'),
    path('update/<int:pk>', views.UpdateDividendIssue.as_view(), name='update-issue'),
    path('delete-issue/<int:pk>', views.DeleteDividendsIssue.as_view(), name='delete-issue'),
    path('member-disbursements/<int:member_id>', views.ListMemberDisbursements.as_view(), name='member-disbursements'),
]

fines/urls.py
from django.urls import path
from . import views


app_name = 'fines'

urlpatterns = [

    path('create-fine/<int:pk>', views.CreateFine.as_view(), name='create-fine'),
    path('pay-fine/<int:pk>', views.PayFine.as_view(), name='pay-fine'),
    path('list-fines/', views.ListFines.as_view(), name='list-fines'),
    path('update-fine/<int:pk>', views.UpdateFine.as_view(), name='update-fine'),
    path('list-member-fines/<int:pk>', views.ListMemberFines.as_view(), name='list-member-fines'),
]

loans/urls.py
from django.urls import path
from loans import views

app_name = 'loans'

urlpatterns = [
    path('', views.ListLoans.as_view(), name='loans'),
    path('view-disbursed-loan/<int:pk>/', views.ViewDisbursedLoan.as_view(), name='view-disbursed-loan'),
    path('armotization-schedule-website/', views.ViewArmotizedScheduleWebsite.as_view(), name='armotization-schedule-website'),
    path('armotization-schedule/', views.ViewArmotizedSchedule.as_view(), name='armotization-schedule'),
    path('disburse-loan/<int:request_id>/', views.DisburseLoan.as_view(), name='disburse-loan'),
    path('approve-loan/<int:pk>/', views.ApproveLoan.as_view(), name='approve-loan'),
    path('list-applications/', views.ListApplications.as_view(), name='list-applications'),
    path('list-disbursements/', views.ListDisbursements.as_view(), name='list-disbursements'),
    path('apply-loan/', views.ApplyLoan.as_view(), name='apply-loan'),
    path('delete/<int:pk>/', views.DeleteLoan.as_view(), name='delete'),
    path('update/<int:pk>/', views.UpdateLoan.as_view(), name='update'),
    path('list', views.ListLoans.as_view(), name='list-loans'),
    path('create-loan/', views.CreateLoanType.as_view(), name='create-loan'),
    path('loan-status/<int:pk>/', views.ShowLoanStatus.as_view(), name='loan-status'),
    path('print-repayment-statement/<int:pk>/', views.PrintRepaymentStatement.as_view(), name='print-repayment-statement'),
    path('print-loan-status/<int:pk>/', views.PrintLoanStatus.as_view(), name='print-loan-status'),
    path('repay-loan/<int:pk>/', views.RepayLoan.as_view(), name='repay-loan'),
    path('request-guarantor/<int:pk>', views.RequestGuarantor.as_view(), name='request-guarantor'),
    path('search-guarantor/<int:pk>', views.SearchGuarantor.as_view(), name='search-guarantor', ),
    path('approve-guarantee-request/<int:pk>', views.ApproveGuaranteeRequest.as_view(), name='approve-guarantee-request', ),
    path('list-guarantee-requests/', views.ListGuaranteeRequests.as_view(), name='list-guarantee-requests', ),
]

members/urls.py
from django.urls import path
from members import views

app_name = 'members'

urlpatterns = [
    path('welcome', views.Welcome.as_view(), name='welcome'),
    path('create-member', views.CreateMember.as_view(), name='create-member'),
    path('admin-create-member', views.AdminCreateMember.as_view(), name='admin-create-member'),
    path('bulk-upload-members', views.BulkMemberUpload.as_view(), name='bulk-upload-members'),
    path('directory', views.MemberDirectory.as_view(), name='directory'),
    path('login', views.Login.as_view(), name='login',),
    path('logout', views.Logout.as_view(), name='logout',),
    path('profile/<int:pk>/', views.MemberProfile.as_view(), name='profile', ),
    path('request-password-reset/', views.RequestPasswordReset.as_view(), name='request-password-reset'),
    path('reset-requested-password/', views.ResetRequestedPassword.as_view(), name='reset-requested-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions', ),
    path('edit-bank-account/<int:account_id>/', views.EditBankAccount.as_view(), name='edit-bank-account', ),
    path('create-bank-account/<int:member_id>/', views.CreateBankAccount.as_view(), name='create-bank-account', ),
    path('edit-member/<int:pk>/', views.EditMember.as_view(), name='edit-member', ),
    path('activate-account/<int:pk>/', views.ActivateAccount.as_view(), name='activate-account', ),
    path('create-password/<int:pk>/', views.CreatePassword.as_view(), name='create-password', ),
    path('change-password/', views.ChangePassword.as_view(), name='change-password', ),
    path('deactivate-account/<int:pk>/', views.DeactivateAccount.as_view(), name='deactivate-account', ),
    path('upload-profile-photo/<int:pk>/', views.UploadProfilePhoto.as_view(), name='upload-profile-photo', ),
    path('print-members-list', views.PrintMembersList.as_view(), name='print-members-list'),
    path('filter-members-list', views.FilterMembersList.as_view(), name='filter-members-list'),
    path('upload-scanned-id/<int:pk>', views.UploadScannedID.as_view(), name='upload-scanned-id'),
    path('', views.MemberDirectory.as_view(), ),
]

opensacco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', home_view.LoadHome.as_view(), name='home'),
    path('send-contact-message', home_view.SendContactMessage.as_view(), name='send-contact-message'),
    path('fines/', include('fines.urls'), name='fines'),
    path('accounting/', include('accounting.urls', namespace='accounting'), name='accounting'),
    path('downloads/', home_view.ViewDownloads.as_view(), name='downloads'),
    path('faqs/', home_view.ViewFAQS.as_view(), name='faqs'),
    path('members/', include('members.urls', namespace='members'), name='members'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('loans/', include('loans.urls', namespace='loans'), name='loans'),
    path('pettycash/', include('pettycash.urls', namespace='pettycash'), name='pettycash'),
    path('dividends/', include('dividends.urls', namespace='dividends'), name='dividends'),
    path('notifications/', include('notifications.urls', namespace='notifications'), name='notifications'),
    path('shares/', include('shares.urls', namespace='shares'), name='shares-home'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from payments import views


app_name = 'payments'

urlpatterns = [
    path('statement/<int:pk>', views.Statement.as_view(), name='statement'),
    path('make-payment-type/', views.MakePaymentType.as_view(), name='make-payment-type'),
    path('upload-contributions/', views.UploadContributions.as_view(), name='upload-contributions'),
    path('list-payments/', views.ListAllPayments.as_view(), name='list-payments'),
    path('make-payment/<int:pk>/', views.MakePayment.as_view(), name='make-payment'),
    path('update-payment/<int:pk>/', views.UpdatePayment.as_view(), name='update-payment'),
    path('list-types/', views.ListPaymentTypes.as_view(), name='list-types'),
    path('update-type/<int:pk>/', views.UpdatePaymentType.as_view(), name='update-type'),
    path('delete-type/<int:pk>/', views.DeletePaymentType.as_view(), name='delete-type'),
    path('print-contributions/', views.PrintContributions.as_view(), name='print-contributions'),
    path('print-statememt/<int:pk>', views.PrintStatement.as_view(), name='print-statement'),
    path('', views.ListPaymentTypes.as_view(), ),
]

shares/urls.py
from django.urls import path
from shares import views

app_name = 'shares'

urlpatterns = [
    path('', views.SharesHome.as_view(), name='shares-home'),
    path('add-shares/<int:pk>/', views.AddShares.as_view(), name='add-shares'),
    path('share-distribution/', views.ShareDistribution.as_view(), name='share-distribution')
]

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from .managers import UserManager
from payments.models import Payment
from django.db.models import Sum
from django.utils.translation import gettext_lazy as _


class Member(AbstractUser):

    member_number = models.CharField(verbose_name=_('Member number'), blank=True, null=True, max_length=50)
    first_name = models.CharField(verbose_name=_('First Name'), blank=False, max_length=100)
    last_name = models.CharField(verbose_name=_('Last Name'), blank=False, max_length=100)
    national_id = models.IntegerField(verbose_name=_('National ID Number'), null=True)
    phone_number = models.CharField(max_length=50, unique=True, verbose_name=_('Phone Number'))
    email = models.EmailField(verbose_name=_('Email'), unique=True, max_length=100, blank=False)
    username = models.CharField(verbose_name=_('User name'), max_length=50, blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)
    profile_photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    scanned_id = models.FileField(upload_to='scanned_ids/', null=True,)
    dob = models.DateField(verbose_name=_('Date of birth'), max_length=250, blank=True, default='1990-01-01')
    nationality = models.CharField(verbose_name=_('Nationality'), max_length=50, blank=True, null=True, default='Kenyan')
    postal_address = models.CharField(verbose_name=_('Postal address'), max_length=200, blank=True, null=True)
    city = models.CharField(verbose_name=_('City'), max_length=200, blank=True, null=True)
    street = models.CharField(verbose_name=_('Street or road'), max_length=200, blank=True, null=True)
    house = models.CharField(verbose_name=_('House or plot number'), max_length=200, blank=True, null=True)
    occupation = models.CharField(verbose_name=_('Occupation'), max_length=200, blank=True, null=True)
    employer = models.CharField(verbose_name=_('Employer'), max_length=250, blank=True)
    marital_status = models.CharField(
        verbose_name=_('Marital Status'),
        max_length=50,
        choices=(
            ('single', _('Single')),
            ('married', _('Married')),
            ('divorced', _('Divorced')),
            ('other', _('Other')),
        ),
        default='single'
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['national_id', 'first_name', 'last_name', 'phone_number']

    class Meta:

        verbose_name = _('member')
        verbose_name_plural = _('members')
        permissions = (
            ('can_view_members', _('Can view members')),
            ('can_change_members', _('Can change members')),
            ('can_delete_members', _('Can delete members')),
        )

    def validate_member_number(self, member_number=''):
        member = Member.objects.get(member_number=member_number)
        if member:
            raise ValidationError(
                _('%(member_number)s already exist'),
                params={'member_number': member_number},
            )

    def get_short_name(self):
        '''
        Returns the last name for the user.
        '''
        return self.last_name

    def member_total_contributions(self,):

        """Returns total contributions of a member"""

        total_contributions = Payment.objects.filter(
            member_id=self.pk,
            payment_type__flag='contribution'
        )

        if len(total_contributions) > 0:

            total = total_contributions.aggregate(Sum('amount'))['amount__sum']

        else:
            total = 0

        return total

    def __str__(self):
        return self.get_full_name()


# class PasswordToken(models.Model):
#     token = models.CharField(max_length=150, blank=False)
#     member = models.ForeignKey(Member, on_delete=models.DO_NOTHING)
#     requested = models.DateTimeField(auto_now_add=True)
#     expired = models.DateTimeField(blank=True)
#     is_active = models.BooleanField(default=True)


class BankAccount(models.Model):
    bank = models.CharField(blank=False, verbose_name='Bank Name', max_length=250)
    account_name = models.CharField(max_length=250)
    account_number = models.CharField(max_length=50, blank=False, unique=True)
    branch = models.CharField(verbose_name='Branch', max_length=150)
    member = models.ForeignKey(Member, blank=False, on_delete=models.DO_NOTHING,)

templates/members/auth_sidebar.html
<div class="scroll-sidebar">
    <nav class="sidebar-nav">
        <ul id="sidebarnav">
            <li>
                <a href="#membersSubmenu" class="waves-effect">
                    <i class="fa fa-users m-r-10" aria-hidden="true"></i>Members
                </a>
                <ul class="collapse list-unstyled" id="membersSubmenu">
                    <li><a href="{% url 'members:directory' %}">View Members</a></li>
                    {% if perms.can_create_member %}
                        <li><a href="{% url 'members:admin-create-member' %}">Add New</a></li>
                        <li><a href="{% url 'members:directory' %}?list=new">New Applications</a></li>
                    {% endif %}
                </ul>
            </li>
        {% if perms.can_change_shares %}
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Shares
                </a>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    <li><a href="{% url 'shares:shares-home' %}">Shares Setup</a></li>
                </ul>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    <li><a href="{% url 'shares:share-distribution' %}">Share Distribution</a></li>
                </ul>
            </li>
        {% endif %}
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Contributions
                </a>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    {% if perms.can_view_payment %}
                    <li><a href="{% url 'payments:list-payments' %}">View Contributions</a></li>
                    {% endif %}
                    {% if perms.can_add_payment %}
                        <li><a href="{% url 'payments:upload-contributions' %}">Upload Contributions</a></li>
                    {% endif %}
                        <li><a href="{% url 'payments:list-types' %}">Contribution Accounts</a></li>
                        <li><a href="{% url 'payments:statement' pk=request.user.pk %}">My Statement</a></li>
                    {% if perms.can_add_paymenttype %}
                        <li><a href="{% url 'payments:make-payment-type' %}">Add Account</a></li>
                    {% endif %}
                </ul>
            </li>
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Loans
                </a>
                <ul class="collapse list-unstyled" id="loansSubmenu">
                    <li><a href="{% url 'loans:list-loans' %}">Loan Products</a></li>
                    {% if perms.loans.add_loan %}
                        <li><a href="{% url 'loans:create-loan' %}">Add New</a></li>
                    {% endif %}
                    {% if perms.loans.view_loans %}
                        <li><a href="{% url 'loans:list-applications' %}">View Applications</a></li>
                    {% endif %}
                    {% if perms.loans.view_loan_disbursements %}
                        <li><a href="{% url 'loans:list-disbursements' %}">View Disbursements</a></li>
                    {% endif %}
                    <li><a href="{% url 'loans:apply-loan' %}">Apply Loan</a></li>
                    <li><a href="{% url 'loans:loan-status' pk=request.user.pk %}">My Loan Status</a></li>
                    <li><a href="{% url 'loans:armotization-schedule' %}">Loan Calculator</a></li>
                    <li><a href="{% url 'loans:list-guarantee-requests' %}">Guarantor requests</a></li>

                </ul>
            </li>
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Dividends
                </a>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    <li><a href="{% url 'dividends:list-issues' %}">View Issues</a></li>
                    {% if perms.can_add_dividendissue %}
                    <li><a href="{% url 'dividends:create-issue' %}">Add New</a></li>
                    {% endif %}
                {% if perms.can_change_loandisbursements %}
                    <li><a href="{% url 'dividends:calculate-dividends' %}">Process Dividends</a></li>
                {% endif %}
                </ul>
            </li>
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-money m-r-10" aria-hidden="true"></i>Fines</a>
                <ul class="collapse list-unstyled" id="finessSubmenu">
                    <li><a href="{% url 'fines:list-member-fines' pk=request.user.pk %}">My Fines</a></li>
                    {% if perms.fines.change_fine %}
                        <li><a href="{% url 'fines:list-fines' %}">Members Fines</a></li>
                    {% endif %}
                </ul>
            </li>
        {% if perms.pettycash.change_expenditure %}
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Petty Cash
                </a>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    <li><a href="{% url 'pettycash:list-expenditures' %}">View Expenditures</a></li>
                    {% if perms.can_view_pettycash %}
                    <li><a href="{% url 'pettycash:add-expenditure' %}">Add New</a></li>
                    {% endif %}
                </ul>
            </li>
        {% endif %}
        {% if perms.pettycash.change_chartofaccounts %}
            <li>
                <a href="#" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Accounting
                </a>
                <ul class="collapse list-unstyled" id="contributionsSubmenu">
                    <li><a href="{% url 'accounting:chart-of-accounts' %}">Chart of Accounts</a></li>
{#                    <li><a href="#">General Ledger</a></li>#}
                    <li><a href="{% url 'accounting:trial-balance' %}">Trial Balance</a></li>

                </ul>
            </li>
        {% endif %}
        {% if request.user.is_superuser %}
            <li>
                <a href="/admin" class="waves-effect"><i class="fa fa-table m-r-10" aria-hidden="true"></i>
                    Admin
                </a>
            </li>
        {% endif%}
        </ul>
    </nav>
    <!-- End Sidebar navigation -->
</div>
<!-- End Sidebar scroll-->

templates/members/deactivate_accounts.html
{% extends 'base.html' %}
{% block title %}Add New Member{% endblock title %}

{% block main-content %}
<form enctype="multipart/form-data" method="post" action="{% url 'members:add-member' %}">{% csrf_token %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Deactivate Member Accounts</h3>
    </div>
<div class="panel-body">

    {% include 'messages.html' %}

    </div><!-- .panel-body -->
    <div class="panel-footer">
        <button class="btn btn-info" type="submit" name="submit"> Submit </button>
    </div>

</div>
</form>
{% endblock main-content %}

templates/members/directory.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Members Directory {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}
    <div class="card mb-0" id="directory">
      <div class="card-header">
        <h2 class="">Members Directory</h2>
      </div>
    <div class="card-body" style="padding: .5rem;">

          {% if members_list|length > 0 %}
              {% include 'members/member-filters-form.html' %}
              <div class="table-responsive table-dark table-hover table-striped">
                  <table class="table">
                      <thead style="font-weight: 900;">
                        <tr>
                            <th>Name</th><th>Number</th><th>Email</th><th>Phone</th><th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for member in members_list %}
                          <tr>
                            <td>
                                <a title="{% if member.is_active and member.member_number is not null %}Active member{% else %}Inactive member{% endif %}" href="{% url 'members:profile' pk=member.pk %}">
                                    <span class="fa fa-{% if member.is_active and member.member_number is not null %}check-square{% else %}minus-square{% endif %}" aria-hidden="true"></span>
                                    &nbsp;{{ member.get_full_name }}
                                </a>
                            </td>
                            <td>{{ member.member_number }}</td>
                            <td>{{ member.email }}</td>
                            <td>{{ member.phone_number }}</td>
                            <td class="non-print-item">
                                <div class="dropdown text-sm-left">
                                  <button class="btn btn-default dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Select<span class="caret"></span>
                                  </button>
                                  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2" style="margin-top: 0px;">
                                    {% if perms.payments.add_payment %}
                                        <li><a href="{% url 'payments:make-payment' pk=member.pk %}" class="nav-link">Make payment</a></li>
                                    {% endif %}
                                    {% if perms.view_payments %}
                                        <li><a href="{% url 'payments:statement' pk=member.pk %}" class="nav-link">View statement</a></li>
                                    {% endif %}
                                    {% if perms.members.change_member %}
                                        <li>
                                            {% if member.is_active and member.member_number is not null %}
                                                <li><a href="#"  class="nav-link" data-toggle="modal" data-target="#deactivate-member-{{ member.pk }}"> Deactivate </a>
                                            {% else %}
                                                <li><a href="#"  class="nav-link" data-toggle="modal" data-target="#activate-member-{{ member.pk }}"> Activate </a>
                                            {% endif %}
                                        </li>
                                    {% endif %}
                                  </ul>

                                </div>
                                <!-- start delete-member-modal -->
                                <div id="delete-member-{{ member.pk }}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4>Delete Member {{ member.first_name }} </h4>
                                            </div>
                                            <div class="modal-body">
                                                <h3 class="text-danger">Are you sure you want to delete {{ member.first_name }} {{ member.last_name }} ?</h3>
                                            </div>
                                            <div class="modal-footer">
                                                <form action="#" method="post" >
                                                    {% csrf_token %}
                                                    <button class="btn btn-danger" type="submit"> Delete </button>
                                                    <button class="btn btn-default" type="button" data-dismiss="modal"> Cancel </button>
                                                </form>
                                            </div>
                                        </div><!-- .modal-content -->
                                    </div>
                                </div>
                                <!-- start deactivate-member-modal -->
                                <div id="deactivate-member-{{ member.pk }}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4>Deactivate Member {{ member.first_name }} </h4>
                                            </div>
                                            <div class="modal-body">
                                                <h3 class="text-danger">Are you sure you want to deactivate {{ member.first_name }} {{ member.last_name }} ?</h3>
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{% url 'members:deactivate-account' pk=member.pk %}" method="post" >
                                                    {% csrf_token %}
                                                    <button class="btn btn-danger" type="submit"> Deactivate </button>
                                                    <button class="btn btn-default" type="button" data-dismiss="modal"> Cancel </button>
                                                </form>
                                            </div>
                                        </div><!-- .modal-content -->
                                    </div>
                                </div>
                                <!-- start activate-member-modal -->
                                <div id="activate-member-{{ member.pk }}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4>Activate Member {{ member.first_name }} </h4>
                                            </div>
                                            <div class="modal-body">
                                                <h3 class="text-danger">Are you sure you want to ACTIVATE {{ member.first_name }} {{ member.last_name }} ?</h3>
                                                <form action="{% url 'members:activate-account' pk=member.pk %}" method="post" >{% csrf_token %}
                                                    {{ activate_account_form.as_p }}
                                                    <button class="btn btn-info" type="submit"> Activate </button>
                                                    <button class="btn btn-default" type="button" data-dismiss="modal"> Cancel </button>
                                                </form>
                                            </div>
                                            <div class="modal-footer">

                                            </div>
                                        </div><!-- .modal-content -->
                                    </div>
                                </div>
                            </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                  </table>
              </div>

          {% else %}
              <div>
              {% include 'members/member-filters-form.html' %}
                <h2> No members found</h2>
              </div>
          {% endif %}
      </div>
    <div class="card-footer">
        <nav aria-label="Members pagination">
            <ul class="pagination pagination-centered">
                {% if members_list.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link"><<</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ members_list.previous_page_number }}" class="page-link"><</a>
                    </li>
                {% endif %}

                {% for i in members_list.paginator.page_range %}
                    <li {% if members_list.number == i %} class="page-item active" {% endif %}>
                        <a href="?page={{i}}" class="page-link">{{i}}<span class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}

                {% if members_list.has_next %}
                    <li class="page-item">
                        <a href="?page={{ members_list.next_page_number }}" class="page-link">></a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ members_list.paginator.num_pages }}" class="page-link">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    </div>
    </div>
{% endblock page_content %}

templates/members/member-filters-form.html
<form action="{% url 'members:directory' %}" method="post" id="filters-form">{% csrf_token %}
    <div class="row non-print-item">
        <div class="col-md-3">
            <input type="text" style="margin: 0;" class="form-control" placeholder="member number" name="member_number">
        </div>
        <div class="col-md-1" style="padding: 0;">
            <input class="btn btn-info" type="submit" value="Search">
        </div>
        <div class="col-md-8">
            <ul class="nav nav-pills pull-right" role="tablist">
                <li role="presentation" class="">
                    <a href="{% url 'members:directory' %}?list=active">Active <span class="badge badge-primary">{{ active_members }}</span></a>
                </li>
                <li role="presentation" class="">
                    <a href="{% url 'members:directory' %}?list=new">Inactive <span class="badge badge-info">{{ inactive_members }}</span></a>
                </li>
                <li role="presentation" class="">
                    <a href="{% url 'members:directory' %}?list=staff">Staff <span class="badge">{{ staff_members }}</span></a>
                </li>
                <li role="presentation" class="">
                    <a href="{% url 'members:filter-members-list' %}" class="btn btn-info">print</a>
                </li>
            </ul>
             <span class=""></span>
        </div>
    </div>
</form>