accounting/urls.py
from django.urls import path
from accounting import views

app_name = 'accounting'

urlpatterns = [
    path('', views.ChartOfAccounts.as_view(), name='chart-of-accounts'),
    path('update-account/<int:pk>', views.UpdateAccount.as_view(), name='update-account'),
    path('account-transactions/<int:pk>', views.ViewAccountTransactions.as_view(), name='account-transactions'),
    path('record-transaction/<int:pk>', views.RecordAccountTransaction.as_view(), name='record-transaction'),
    path('update-transaction/<int:pk>', views.UpdateAccountTransaction.as_view(), name='update-transaction'),
    path('delete-transaction/<int:pk>', views.DeleteTransaction.as_view(), name='delete-transaction'),
    path('delete-account/<int:pk>', views.DeleteAccount.as_view(), name='delete-account'),
    path('create-account/', views.CreateAccount.as_view(), name='create-account'),
    path('update-account-group/<int:pk>', views.UpdateAccountGroup.as_view(), name='update-account-group'),
    path('delete-account-group/<int:pk>', views.DeleteAccountGroup.as_view(), name='delete-account-group'),
    path('create-account-group/', views.CreateAccountGroup.as_view(), name='create-account-group'),
    path('trial-balance/', views.TrialBalance.as_view(), name='trial-balance'),
]

fines/urls.py
from django.urls import path
from . import views


app_name = 'fines'

urlpatterns = [

    path('create-fine/<int:pk>', views.CreateFine.as_view(), name='create-fine'),
    path('pay-fine/<int:pk>', views.PayFine.as_view(), name='pay-fine'),
    path('list-fines/', views.ListFines.as_view(), name='list-fines'),
    path('update-fine/<int:pk>', views.UpdateFine.as_view(), name='update-fine'),
    path('list-member-fines/<int:pk>', views.ListMemberFines.as_view(), name='list-member-fines'),
]

opensacco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', home_view.LoadHome.as_view(), name='home'),
    path('send-contact-message', home_view.SendContactMessage.as_view(), name='send-contact-message'),
    path('fines/', include('fines.urls'), name='fines'),
    path('accounting/', include('accounting.urls', namespace='accounting'), name='accounting'),
    path('downloads/', home_view.ViewDownloads.as_view(), name='downloads'),
    path('faqs/', home_view.ViewFAQS.as_view(), name='faqs'),
    path('members/', include('members.urls', namespace='members'), name='members'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('loans/', include('loans.urls', namespace='loans'), name='loans'),
    path('pettycash/', include('pettycash.urls', namespace='pettycash'), name='pettycash'),
    path('dividends/', include('dividends.urls', namespace='dividends'), name='dividends'),
    path('notifications/', include('notifications.urls', namespace='notifications'), name='notifications'),
    path('shares/', include('shares.urls', namespace='shares'), name='shares-home'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounting/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, FormView, TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from accounting.models import AccountGroup, Account, AccountTransaction
from accounting.forms import CreateAccountGroupForm, UpdateAccountGroupForm, CreateAccountForm, UpdateAccountForm, CreateTransactionForm, UpdateTransactionForm
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.mixins import PermissionRequiredMixin
from accounting.utils import get_account_balance


class DeleteTransaction(PermissionRequiredMixin, DeleteView):
    model = AccountTransaction
    permission_required = 'accounting.change_accounttransaction'
    raise_exception = True
    success_url = '/accounting/'

    def get_success_url(self):

        messages.success(self.request, 'Transaction has been deleted', extra_tags='alert alert-danger')

        return self.success_url


class UpdateAccountTransaction(PermissionRequiredMixin, FormView):
    permission_required = 'accounting.change_accounttransaction'
    raise_exception = True
    template_name = 'accounting/update_transaction.html'
    form_class = UpdateTransactionForm

    def post(self, request, *args, **kwargs):

        transaction = get_object_or_404(AccountTransaction, pk=self.kwargs['pk'])

        form = self.form_class(data=request.POST, instance=transaction)

        if form.is_valid():

            updated_transaction = form.save(commit=False)
            updated_transaction.staff_id = self.request.user.pk
            updated_transaction.save()

            messages.success(request, 'Success, transaction has been updated', extra_tags='alert alert-success')

            return redirect(to='accounting:update-transaction', pk=self.kwargs['pk'])
        else:
            messages.error(request, 'Failed, form errors occurred', extra_tags='alert alert-danger')

        account = get_object_or_404(Account, pk=transaction.account_id)

        transactions = AccountTransaction.objects.filter(account_id=transaction.account_id)

        context = {
            'account': account,
            'transaction': transaction,
            'transactions': transactions,
            'form': form
        }
        return render(request, self.template_name, context=context)

    def get(self, request, *args, **kwargs):

        transaction = get_object_or_404(AccountTransaction, pk=self.kwargs['pk'])

        form = self.form_class(instance=transaction)

        account = get_object_or_404(Account, pk=transaction.account_id)

        transactions = AccountTransaction.objects.filter(account_id=transaction.account_id)

        context = {
            'account': account,
            'form': form,
            'transaction': transaction,
            'transactions': transactions
        }

        return render(request, self.template_name, context=context)


class RecordAccountTransaction(PermissionRequiredMixin, FormView):
    template_name = 'accounting/record_transactions.html'
    form_class = CreateTransactionForm
    permission_required = 'accounting.add_accounttransaction'
    raise_exception = True

    def post(self, request, *args, **kwargs):

        account = Account.objects.filter(pk=self.kwargs['pk'])

        form = self.form_class(data=request.POST)

        if form.is_valid():

            transaction = form.save(commit=False)
            transaction.account_id = self.kwargs['pk']
            transaction.staff_id = self.request.user.pk
            transaction.save()

            messages.success(request, 'Success, transaction has been recorded', extra_tags='alert alert-success')

            return redirect(to='accounting:record-transaction', pk=self.kwargs['pk'])

        else:

            messages.error(request, 'Error, transaction not recorded', extra_tags='alert alert-danger')

        transactions = AccountTransaction.objects.filter(account_id=self.kwargs['pk'])

        context = {
            'form': form,
            'account': account.get(),
            'transactions': transactions
        }
        return render(request, self.template_name, context=context)

    def get(self, request, *args, **kwargs):

        account = Account.objects.filter(pk=self.kwargs['pk'])

        transactions = AccountTransaction.objects.filter(account_id=self.kwargs['pk'])

        form = self.form_class

        context = {
            'form': form,
            'account': account.get(),
            'transactions': transactions
        }
        return render(request, self.template_name, context=context)


class ViewAccountTransactions(PermissionRequiredMixin, TemplateView):
    template_name = 'accounting/account_transactions.html'
    permission_required = 'accounting.add_accounttransaction'
    raise_exception = True

    def get(self, request, *args, **kwargs):

        account = get_object_or_404(Account, pk=self.kwargs['pk'])

        transactions = AccountTransaction.objects.filter(account_id=self.kwargs['pk'])

        context = {
            'account': account,
            'transactions': transactions,
            'account_sum': transactions.aggregate(Sum('amount'))['amount__sum']
        }
        return render(request, self.template_name, context=context)


class TrialBalance(PermissionRequiredMixin, FormView):
    template_name = 'accounting/trial_balance.html'
    permission_required = 'accounting.add_account'
    raise_exception = True

    def get(self, request, *args, **kwargs):

        account_groups = AccountGroup.objects.all().order_by('group_number')

        groups_list = []
        debit_total = 0
        credit_total = 0

        for group in account_groups:

            group_children = group.get_children()
            children_data = []

            for account in group_children:

                if request.GET.get('status') == 'active' and account.status == 'closed':
                    continue

                if request.GET.get('status') == 'closed' and account.status == 'active':
                    continue

                account_balance = get_account_balance(account, request)

                children_data.append({
                    'account_number': account.account_number,
                    'account_name': account.account_name,
                    'account_balance': account_balance,
                    'increases': account.increases
                })

                if account.increases == 'credit':
                    credit_total += account_balance
                else:
                    debit_total += account_balance

            groups_list.append({
                'group_name': group.group_name,
                'group_number': group.group_number,
                'children_data': children_data
            })

        context = {
            'accounts_dict': groups_list,
            'credit_total': credit_total,
            'debit_total': debit_total
        }

        return render(request, self.template_name, context=context)


class CreateAccount(PermissionRequiredMixin, FormView):
    permission_required = 'accounting.add_account'
    raise_exception = True
    template_name = 'accounting/create_account.html'
    form_class = CreateAccountForm
    success_url = '/accounting/create-account'

    def get(self, request, *args, **kwargs):

        context = {
            'accounts_list': Account.objects.all().order_by('account_number'),
            'form': self.form_class
        }

        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():

            account = Account(
                account_number=form.cleaned_data['account_number'],
                account_name=form.cleaned_data['account_name'],
                account_type=form.cleaned_data['account_type'],
                account_group=form.cleaned_data['account_group'],
                opening_balance=form.cleaned_data['opening_balance'],
                opening_date=form.cleaned_data['opening_date'],
                increases=form.cleaned_data['increases'],
                inherits=form.cleaned_data['inherits'],
                description=form.cleaned_data['description']
            )

            account.save()

            messages.success(request, 'Account has been created', extra_tags='alert alert-success')

            return redirect(to='accounting:create-account')

        else:
            messages.error(request, 'Error, account not created', extra_tags='alert alert-danger')

        context = {
            'accounts_list': Account.objects.all().order_by('account_number'),
            'form': self.form_class
        }

        return render(request, self.template_name, context=context)


class DeleteAccount(PermissionRequiredMixin, DeleteView):
    model = Account
    permission_required = 'accounting.change_account'
    raise_exception = True
    success_url = '/accounting/create-account'

    def get_success_url(self):

        messages.success(self.request, 'Account has been deleted', extra_tags='alert alert-danger')

        return self.success_url


class UpdateAccount(PermissionRequiredMixin, FormView):
    permission_required = 'accounting.change_account'
    raise_exception = True
    template_name = 'accounting/update_account.html'
    form_class = UpdateAccountForm

    def get(self, request, *args, **kwargs):

        account = get_object_or_404(Account, pk=self.kwargs['pk'])

        initial = {
            'account_number': account.account_number,
            'account_name': account.account_name,
            'account_group': account.account_group,
            'account_type': account.account_type,
            'increases': account.increases,
            'opening_balance': account.opening_balance,
            'opening_date': account.opening_date,
            'status': account.status,

templates/accounting/accountgroup_confirm_delete.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Create Account Group {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account' %}">Create New Account</a>
            </li>
        </ul>
        <div class="row">
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Delete {{ accountgroup.group_name }} </h3>
                        </div>
                        <div class="card-body pt-3 text-center">
                            <form action="" method="post">{% csrf_token %}
                                <h5 class="text-danger">Are you sure you want to delete <strong>{{ accountgroup.group_name }} ?</strong></h5>
                                <div class="row p-3">
                                    <div class="col-6">
                                        <a class="btn btn-info" href="{% url 'accounting:create-account-group' %}">
                                            Cancel <i class="fa fa-cancel"></i>
                                        </a>
                                    </div>
                                    <div class="col-6">
                                        <button class="btn btn-info" type="submit" value="Confirm" >
                                            Proceed <i class="fa fa-send"></i>
                                        </button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Accounts in Group</h3>
                        </div>
                        <div class="card-body pt-3">

                        </div>
                    </div>
                </div>
            </div>

            </div>
        </div>
    </div>
{% endblock page_content %}

templates/accounting/accounttransaction_confirm_delete.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Delete Transaction {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account' %}">Create Account</a>
            </li>
        </ul>
        <div class="row">
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Delete transaction </h3>
                        </div>
                        <div class="card-body pt-3 text-center">
                            <form action="{% url 'accounting:delete-transaction' pk=accounttransaction.pk %}" method="post">{% csrf_token %}
                                <h5 class="text-danger">Are you sure you want to delete this transaction
                                    <strong>{{ account.account_name }} ?</strong>
                                </h5>
                                <div class="row p-3">
                                    <div class="col-6">
                                        <a class="btn btn-info" href="{% url 'accounting:chart-of-accounts'  %}">
                                            Cancel <i class="fa fa-cancel"></i>
                                        </a>
                                    </div>
                                    <div class="col-6">
                                        <button class="btn btn-info" type="submit" value="Confirm" >
                                            Proceed <i class="fa fa-send"></i>
                                        </button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Accounts in Group</h3>
                        </div>
                        <div class="card-body pt-3">

                        </div>
                    </div>
                </div>
            </div>

            </div>
        </div>
    </div>
{% endblock page_content %}

templates/accounting/create_account.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Create Account {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:chart-of-accounts' %}">
                    <i class="fa fa-list"></i> Chart of Accounts
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account-group' %}"><i class="fa fa-plus"></i> Create Group</a>
            </li>
        </ul>
        <div class="row">
            <div class="col-lg-7 col-md-7">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Accounts List</h3>
                        </div>
                        <div class="card-body pt-3">
                            {% if accounts_list|length > 0 %}
                                <table class="table table-responsive table-striped">
                                <thead>
                                    <th>Account</th><th>Increases</th><th>Type</th>
                                </thead>
                                    {% for account in accounts_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'accounting:update-account' pk=account.pk %}">
                                                    {{ account.account_number }}: {{ account.account_name }}
                                                </a>
                                            </td>
                                            <td>{{ account.increases|capfirst }}</td>
                                            <td>{{ account.account_type|capfirst }}</td>
                                            <td class="">
                                                {% if account.inherits == 'none' %}
                                                    <a href="{% url 'accounting:account-transactions' pk=account.pk %}">
                                                        <i class="fa fa-th-list"></i>
                                                    </a>
                                                {% else %}
                                                    --
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% else %}
                                <div class="alert alert-info">
                                    No accounts exist here yet ...
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-5">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Create New Account</h3>
                        </div>
                        <div class="card-body pt-3">
                            <form method="post" class="" action="{% url 'accounting:create-account' %}">{% csrf_token %}
                            {{ form.as_p }}
                                <p class="text-right">
                                <button type="submit" class="form-group btn btn-info">Create <i class="fa fa-send"></i></button>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            </div>
        </div>
    </div>
{% endblock page_content %}

templates/accounting/create_accountgroup.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Create Account Group {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account' %}">
                    <i class="fa fa-plus"></i> Create Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:chart-of-accounts' %}">
                    <i class="fa fa-list"></i> Chart of accounts
                </a>
            </li>
        </ul>
        <div class="row">
            <div class="col-lg-7 col-md-7">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Account Groups</h3>
                        </div>
                        <div class="card-body pt-3">
                            {% if account_groups|length > 0 %}
                                <table class="table table-responsive table-striped">
                                {% for account_group in account_groups %}
                                    <tr>
                                        <td>{{ account_group.group_number }}: {{ account_group.group_name }}</td>
                                        <td>
                                            <a href="{% url 'accounting:update-account-group' pk=account_group.pk %}">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'accounting:delete-account-group' pk=account_group.pk %}">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </table>
                            {% else %}
                                <div class="alert alert-info"> No accounts groups on the database yet ...
                                    <a href="{% url 'accounting:create-account-group' %}">create new</a>
                                </div>
                            {% endif %}
                        </div><!-- .card-body -->
                    </div>
                </div><!-- .card -->
            </div>
            <div class="col-lg-5 col-md-5">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Create New Group</h3>
                        </div>
                        <div class="card-body pt-3">
                            <form method="post" class="" action="{% url 'accounting:create-account-group' %}">{% csrf_token %}
                            {{ form.as_p }}
                                <p class="text-right">
                                <button type="submit" class="form-group btn btn-info">Create <i class="fa fa-send"></i></button>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            </div>
        </div>
    </div>
{% endblock page_content %}

templates/accounting/update_account.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Update Account {{ account.account_name }} {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:chart-of-accounts' %}">
                    <i class="fa fa-list"></i> Chart of Accounts
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account' %}"><i class="fa fa-plus"></i> Create Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounting:create-account-group' %}">
                    <i class="fa fa-list-ul"></i> Account Groups
                </a>
            </li>
        </ul>
        <div class="row">
            <div class="col-lg-7 col-md-7">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Accounts List</h3>
                        </div>
                        <div class="card-body pt-3">
                            {% if accounts_list|length > 0 %}
                                <table class="table table-responsive table-striped">
                                <thead>
                                    <th>Account</th><th>Increases</th><th>Type</th>
                                </thead>
                                    {% for account in accounts_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'accounting:update-account' pk=account.pk %}">
                                                    {{ account.account_number }}: {{ account.account_name }}
                                                </a>
                                            </td>
                                            <td>{{ account.increases|capfirst }}</td>
                                            <td>{{ account.account_type|capfirst }}</td>
                                            <td class="">
                                                {% if account.inherits == 'none' %}
                                                    <a href="{% url 'accounting:account-transactions' pk=account.pk %}">
                                                        <i class="fa fa-th-list"></i>
                                                    </a>
                                                {% else %}
                                                    --
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% else %}
                                <div class="alert alert-info">
                                    No accounts exist here yet ...
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-5">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header">
                            <h3 class="card-title pt-2 pl-2">Update {{ account.account_name }}</h3>
                        </div>
                        <div class="card-body pt-3">
                            <form method="post" class="" action="{% url 'accounting:update-account' pk=account.pk %}">{% csrf_token %}
                            {{ form.as_p }}
                                <div class="row text-center">
                                    <div class="col">
                                        <a title="Delete" href="{% url 'accounting:delete-account' pk=account.pk %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="form-group btn btn-info">Update <i class="fa fa-send"></i></button>
                                    </div>
                                </div>
                                <p class="text-right">

                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock page_content %}