fines/urls.py
from django.urls import path
from . import views


app_name = 'fines'

urlpatterns = [

    path('create-fine/<int:pk>', views.CreateFine.as_view(), name='create-fine'),
    path('pay-fine/<int:pk>', views.PayFine.as_view(), name='pay-fine'),
    path('list-fines/', views.ListFines.as_view(), name='list-fines'),
    path('update-fine/<int:pk>', views.UpdateFine.as_view(), name='update-fine'),
    path('list-member-fines/<int:pk>', views.ListMemberFines.as_view(), name='list-member-fines'),
]

members/urls.py
from django.urls import path
from members import views

app_name = 'members'

urlpatterns = [
    path('welcome', views.Welcome.as_view(), name='welcome'),
    path('create-member', views.CreateMember.as_view(), name='create-member'),
    path('admin-create-member', views.AdminCreateMember.as_view(), name='admin-create-member'),
    path('bulk-upload-members', views.BulkMemberUpload.as_view(), name='bulk-upload-members'),
    path('directory', views.MemberDirectory.as_view(), name='directory'),
    path('login', views.Login.as_view(), name='login',),
    path('logout', views.Logout.as_view(), name='logout',),
    path('profile/<int:pk>/', views.MemberProfile.as_view(), name='profile', ),
    path('request-password-reset/', views.RequestPasswordReset.as_view(), name='request-password-reset'),
    path('reset-requested-password/', views.ResetRequestedPassword.as_view(), name='reset-requested-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions', ),
    path('edit-bank-account/<int:account_id>/', views.EditBankAccount.as_view(), name='edit-bank-account', ),
    path('create-bank-account/<int:member_id>/', views.CreateBankAccount.as_view(), name='create-bank-account', ),
    path('edit-member/<int:pk>/', views.EditMember.as_view(), name='edit-member', ),
    path('activate-account/<int:pk>/', views.ActivateAccount.as_view(), name='activate-account', ),
    path('create-password/<int:pk>/', views.CreatePassword.as_view(), name='create-password', ),
    path('change-password/', views.ChangePassword.as_view(), name='change-password', ),
    path('deactivate-account/<int:pk>/', views.DeactivateAccount.as_view(), name='deactivate-account', ),
    path('upload-profile-photo/<int:pk>/', views.UploadProfilePhoto.as_view(), name='upload-profile-photo', ),
    path('print-members-list', views.PrintMembersList.as_view(), name='print-members-list'),
    path('filter-members-list', views.FilterMembersList.as_view(), name='filter-members-list'),
    path('upload-scanned-id/<int:pk>', views.UploadScannedID.as_view(), name='upload-scanned-id'),
    path('', views.MemberDirectory.as_view(), ),
]

opensacco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', home_view.LoadHome.as_view(), name='home'),
    path('send-contact-message', home_view.SendContactMessage.as_view(), name='send-contact-message'),
    path('fines/', include('fines.urls'), name='fines'),
    path('accounting/', include('accounting.urls', namespace='accounting'), name='accounting'),
    path('downloads/', home_view.ViewDownloads.as_view(), name='downloads'),
    path('faqs/', home_view.ViewFAQS.as_view(), name='faqs'),
    path('members/', include('members.urls', namespace='members'), name='members'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('loans/', include('loans.urls', namespace='loans'), name='loans'),
    path('pettycash/', include('pettycash.urls', namespace='pettycash'), name='pettycash'),
    path('dividends/', include('dividends.urls', namespace='dividends'), name='dividends'),
    path('notifications/', include('notifications.urls', namespace='notifications'), name='notifications'),
    path('shares/', include('shares.urls', namespace='shares'), name='shares-home'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from payments import views


app_name = 'payments'

urlpatterns = [
    path('statement/<int:pk>', views.Statement.as_view(), name='statement'),
    path('make-payment-type/', views.MakePaymentType.as_view(), name='make-payment-type'),
    path('upload-contributions/', views.UploadContributions.as_view(), name='upload-contributions'),
    path('list-payments/', views.ListAllPayments.as_view(), name='list-payments'),
    path('make-payment/<int:pk>/', views.MakePayment.as_view(), name='make-payment'),
    path('update-payment/<int:pk>/', views.UpdatePayment.as_view(), name='update-payment'),
    path('list-types/', views.ListPaymentTypes.as_view(), name='list-types'),
    path('update-type/<int:pk>/', views.UpdatePaymentType.as_view(), name='update-type'),
    path('delete-type/<int:pk>/', views.DeletePaymentType.as_view(), name='delete-type'),
    path('print-contributions/', views.PrintContributions.as_view(), name='print-contributions'),
    path('print-statememt/<int:pk>', views.PrintStatement.as_view(), name='print-statement'),
    path('', views.ListPaymentTypes.as_view(), ),
]

payments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# from members.models import Member
from django.conf import settings
from django.db.models import Sum


class PaymentType(models.Model):

    payment_type = models.CharField(
        verbose_name=_('Payment type'),
        max_length=150, blank=False,
        unique=True
    )
    frequency = models.CharField(
        verbose_name=_('Frequency'),
        choices=(('UNSET', 'Unset'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')),
        default='UNSET', max_length=100,
    )
    min_amount = models.IntegerField(verbose_name=_('Minimum amount'), blank=False)
    date_created = models.DateTimeField(verbose_name='Date created', auto_now=True)
    is_active = models.BooleanField(default=True)
    slug = models.CharField(default=str(payment_type).replace(' ', '_').lower(), max_length=250)
    flag = models.CharField(
        verbose_name='Flag',
        choices=(
            ('saving_account', 'Saving account'),
            ('registration_fee', 'Registration Fees'),
        ),
        default='saving_account',
        max_length=150,
    )

    def __str__(self):
        return self.payment_type

    class Meta:
        permissions = (
            ('view_payment_type', 'Can view payment types'),
        )


class Payment(models.Model):

    member = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Members name'),
        related_name='member',
        on_delete=models.DO_NOTHING
    )
    payment_type = models.ForeignKey(PaymentType, on_delete=models.DO_NOTHING, verbose_name='Payment category')
    amount = models.FloatField(verbose_name=_('Amount'), blank=False)
    date = models.DateTimeField(verbose_name=_('Date time'),)
    paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Paid by'),
        on_delete=models.DO_NOTHING,
        related_name='staff',
    )
    notes = models.TextField(verbose_name=_('Notes'), max_length=1000, blank=True)
    total = models.FloatField(verbose_name=_('Total'), blank=False, default=0)

    class Meta:
        permissions = (
            ('view_own_payment', 'Can view own payments'),
            ('view_all_payments', 'Can view all payments'),
        )

    def loan_amount_repaid_by_member(self, member_id):
        total_loans_repaid = Payment.objects.filter(
            member_id=member_id,
            payment_type__flag='loan_repayment'
        ).aggregate(Sum('amount'))

        return total_loans_repaid

    def __str__(self):
        return self.member.last_name + ' : ' + str(self.amount)

payments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (DeleteView, CreateView, ListView, UpdateView, FormView,)
from payments.models import (PaymentType, Payment)
from payments.forms import (UpdatePaymentForm, PaymentTypeForm, UpdatePaymentTypeForm, PaymentForm, AllPaymentsFiltersForm, UploadContributionsForm,)
from django.contrib import messages
from members.models import Member
from datetime import datetime
from django.core.exceptions import ValidationError, ObjectDoesNotExist
import pandas as pd
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from reports.models import TrialBalance
from easy_pdf.views import PDFTemplateView
from django.db.models import Sum
from django.contrib.auth import (PermissionDenied,)
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin,)
from accounting.models import Account, AccountGroup, BuiltInAccount
import random


class PrintStatement(PDFTemplateView):
    permission_denied_message = 'You dont have permission to print member statement'
    raise_exception = True
    permission_required = 'payments:view_payments'
    template_name = 'payments/print-statement-pdf.html'

    def get_context_data(self, **kwargs):

        context = super(PrintStatement, self).get_context_data(**kwargs)

        member = get_object_or_404(Member, pk=self.kwargs['pk'])

        context['title'] = 'Payments statement : ' + member.get_full_name()

        date_from = '2000-01-01 00:00:00'
        date_to = '2100-12-31 23:59:59'

        if self.request.GET.get('date_from'):
            date_from = self.request.GET.get('date_from')

        if self.request.GET.get('date_to'):
            date_to = self.request.GET.get('date_to')

        if self.request.GET.get('payment_type'):

            context['contributions'] = Payment.objects.filter(
                payment_type=self.request.GET.get('payment_type'),
                date__gte=date_from + ' 00:00:00',
                date__lte=date_to + ' 23:59:59',
                member_id=self.kwargs['pk']
            )
        else:
            context['contributions'] = Payment.objects.filter(
                date__gte=date_from + ' 00:00:00',
                member_id=self.kwargs['pk'],
                date__lte=date_to + ' 23:59:59'
            )

        return context


class PrintContributions(PDFTemplateView):
    permission_denied_message = 'You dont have permission to print contributions list'
    raise_exception = True
    permission_required = 'payments:view_payments'
    template_name = 'payments/print-payments-pdf.html'

    def get_context_data(self, **kwargs):

        context = super(PrintContributions, self).get_context_data(**kwargs)

        context['title'] = 'Payments statement'

        date_from = '2000-01-01 00:00:00'
        date_to = '2100-12-31 23:59:59'

        if self.request.GET.get('date_from'):
            date_from = self.request.GET.get('date_from')

        if self.request.GET.get('date_to'):
            date_to = self.request.GET.get('date_to')

        if self.request.GET.get('payment_type'):

            context['contributions'] = Payment.objects.filter(
                payment_type=self.request.GET.get('payment_type'),
                date__gte=date_from + ' 00:00:00',
                date__lte=date_to + ' 23:59:59'
            )
        else:
            context['contributions'] = Payment.objects.filter(
                date__gte=date_from + ' 00:00:00',
                date__lte=date_to + ' 23:59:59'
            )

        return context


class UploadContributions(PermissionRequiredMixin, CreateView):
    model = Payment
    permission_required = 'Add Payment'
    raise_exception = True
    permission_denied_message = 'You dont have permission to Upload contributions'
    template_name = 'payments/upload-contributions.html'

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name, {'form': UploadContributionsForm})

    def post(self, request, *args, **kwargs):

        form = UploadContributionsForm(data=request.POST, files=request.FILES)
        payments = []
        fails = 0
        exceptions = []

        if form.is_valid():

            if ".xlsx" not in request.FILES['file'].name:
                raise ValidationError("Filetype is not valid MS excel.")

            df = pd.read_excel(request.FILES['file'])

            for index, row in df.iterrows():

                try:
                    payment_type = PaymentType.objects.get(pk=row['payment_code'])

                except ObjectDoesNotExist as exp:

                    exceptions.append(

                        str(row['payment_code']) + " : " + str(exp)
                    )
                    continue

                try:
                    member = Member.objects.get(member_number=row['member_number'])
                except ObjectDoesNotExist as exp:
                    exceptions.append(
                        str(row['member_number']) + " : " + str(exp)
                    )
                    continue

                if payment_type.flag == 'contribution':

                    total = float(member.member_total_contributions()) + float(row['amount'])

                else:
                    total = float(row['amount'])

                try:
                    single_payment = Payment(
                        amount=row['amount'],
                        member=member,
                        payment_type=payment_type,
                        paid_by_id=self.request.user.pk,
                        date=pd.to_datetime(row['date']),
                        total=total
                    )

                    single_payment.save()

                    trial_balance = TrialBalance(
                        credit=row['amount'],
                        timestamp=single_payment.date,
                        debit=0.0,
                        module='Contributions',
                        member=member,
                        staff=self.request.user.get_full_name(),
                        description=payment_type
                    )

                    trial_balance.save()

                    payments.append(single_payment)

                except Exception as exp:

                    exceptions.append(exp)

                    fails += 1
        else:

            messages.error(request, 'Errors occured', extra_tags='alert alert-danger')
        #
        context = {
            'form': form,
            'fails': fails,
            'exceptions': exceptions,
            'payments': payments,
        }
        return render(request, self.template_name, context=context)


class UpdatePayment(PermissionRequiredMixin, UpdateView):
    model = Payment
    permission_required = 'payments.change_payment'
    template_name = 'payments/update-payment.html'

    def get(self, request, *args, **kwargs):

        payment = get_object_or_404(Payment, pk=self.kwargs['pk'])

        member = Member.objects.filter(pk=payment.member.id)

        initial = {
            'member': member.get(),
            'amount': payment.amount,
            'date': payment.date,
            'paid_by': self.request.user,
            'payment_type': payment.payment_type,
            'notes': payment.notes
        }

        context = {
            'form': UpdatePaymentForm(member=member, initial=initial)
        }

        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):

        payment = get_object_or_404(Payment, pk=self.kwargs['pk'])

        member = Member.objects.filter(pk=payment.member.id)

        form = UpdatePaymentForm(member=member, data=request.POST, instance=payment)

        if form.is_valid():

            pay = form.save(commit=False)

            pay.paid_by_id = self.request.user.pk

            pay.save()

            messages.success(request, 'Sucess, payment updated', extra_tags='alert alert-success')

            return redirect(to='payments:statement', pk=member.get().pk)
        else:
            messages.error(request, 'Failed, errors occured', extra_tags='alert alert-danger')

            context = {
                'form': form
            }

            return render(request, self.template_name, context=context)


class MakePayment(PermissionRequiredMixin, CreateView):
    model = Payment
    template_name = 'payments/make-payment.html'
    form_class = PaymentForm
    permission_required = 'payments.add_payment'
    raise_exception = True
    permission_denied_message = 'You dont have permission to access this page'

    def get(self, request, *args, **kwargs):

        member = Member.objects.filter(pk=self.kwargs['pk'])
        paid_by = Member.objects.filter(pk=self.request.user.pk)

        payment = Payment.objects.filter(member=self.kwargs['pk']).last()

        payment_types = PaymentType.objects.filter(is_active=True)

        if not payment:
            last_total = 0
        else:
            last_total = payment.total

        initial = {'total': last_total}

        self.form_class = PaymentForm(member=member, paid_by=paid_by, payment_types=payment_types, initial=initial)

        context = {
            'form': self.form_class,
            'upload_form': UploadContributionsForm,
            'member': member.get()
        }

        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):

        if not (self.request.user.is_superuser or self.request.user.is_staff):
            raise PermissionDenied

        member = Member.objects.filter(pk=self.kwargs['pk'])
        paid_by = Member.objects.filter(pk=self.request.user.pk)

        payment_types = PaymentType.objects.filter(is_active=True)

        form = PaymentForm(data=request.POST, member=member, paid_by=paid_by, payment_types=payment_types)

        if form.is_valid():

templates/payments/list-payments.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Member contributions {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}
    <div class="member-functions">
        <ul class="nav nav-pills justify-content-end pb-1">
            <li class="nav-item">
                <a class="nav-link " href="#">Total: <strong>KSHS {{ total_payments.amount__sum }}</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Contributions: <strong>KSHS {{ total_contributions.amount__sum }}</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Loans: <strong>KSHS {{ total_loans_repaid.amount__sum }}</strong></a>
            </li>
            <li class="nav-item">
                <a href="#" data-toggle="modal" data-target="#filtersModal">
                    <i class="fa fa-print" aria-hidden="true"></i> Print
                </a>
            </li>
        </ul>
        <!-- Modal -->
        <div class="modal fade" id="filtersModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <form action="{% url 'payments:print-contributions' %}" method="get" class="modal-content" id="filters-form">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title text-left" id="myModalLabel">Create Print Filters on Contributions</h4>
                    </div>
                    <div class="modal-body">
                        {{ filters_form }}
                        <div>
                            <label for="date_from">Date from: </label>
                            <input id="date_from" name="date_from" type="text" class="form-control" required />
                        </div>
                        <div>
                            <label for="date_to">Date to: </label>
                            <input id="date_to" name="date_to" type="text" class="form-control" required />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </form>
            </div>
        </div><!-- end-Modal -->
    </div>
    <div class="card mb-0" id="directory">
      <div class="card-header">
        <h2 class="">Member Contributions
            {% if date_from %} from {{ date_from }}{% endif %}
            {% if date_to %} to {{ date_to }}
            {% else %}
                as at {% now "jS F Y H:i:s" %}
            {% endif %}
        </h2>
      </div>

    <div class="card-body" style="padding: .5rem;">

          {% if contributions|length > 0 %}

              <div class="table-responsive table-dark table-hover table-striped">
                  <table class="table">
                      <thead style="font-weight: 900;">
                        <tr>
                            <th>Date</th><th>Member</th><th class="text-right">Amount</th><th>For</th><th>Staff</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for contribution in contributions %}
                          <tr>
                              <td>
                                  {% if perms.payments.update_payment %}
                                      <a href="{% url 'payments:update-payment' pk=contribution.pk %}" >
                                        {{ contribution.date|date:'d/m/Y H:i:s' }}
                                      </a>
                                  {% else %}
                                        {{ contribution.date|date:'d/m/Y H:i:s' }}
                                  {% endif %}
                              </td>
                              <td>
                                  <a href="{% url 'members:profile' pk=contribution.member.pk %}" title="view statement">
                                      {{ contribution.member.get_full_name }}
                                  </a>
                              </td>
                              <td class="text-right">{{ contribution.amount }}</td>
                              <td>{{ contribution.payment_type }}</td>
                              <td>{{ contribution.paid_by }}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                  </table>
              </div>

          {% else %}
              <div>
                <h2> No payments yet</h2>
              </div>
          {% endif %}
      </div>
    <div class="card-footer">
        <nav aria-label="Members pagination">
            <ul class="pagination pagination-centered">
                {% if contributions.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link"><<</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ contributions.previous_page_number }}" class="page-link"><</a>
                    </li>
                {% endif %}

                {% for i in contributions.paginator.page_range %}
                    <li {% if contributions.number == i %} class="page-item active" {% endif %}>
                        <a href="?page={{i}}" class="page-link">{{i}}<span class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}

                {% if contributions.has_next %}
                    <li class="page-item">
                        <a href="?page={{ contributions.next_page_number }}" class="page-link">></a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ contributions.paginator.num_pages }}" class="page-link">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    </div>
{% endblock page_content %}

templates/payments/list-types.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Payment Types {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}

        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a href="{% url 'payments:make-payment-type' %}" class="nav-link">Create New</a>
            </li>
        </ul>
    <div class="card mb-0" id="directory">
      <div class="card-header">
        <h2 class="">Contribution Accounts</h2>
      </div>

    <div class="card-body" style="padding: .5rem;">

          {% if paymenttype_list|length > 0 %}

              <div class="table-responsive table-dark table-hover">
                  <table class="table">
                      <thead style="font-weight: 900;">
                        <tr>
                            <th>Code</th><th>Account</th><th>Frequency</th><th>Min. amount</th><th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for paymenttype in paymenttype_list %}
                          <tr>
                            <td>{{ paymenttype.pk }}</td>
                            <td>
                                <a href="{% url 'payments:update-type' pk=paymenttype.pk %}">
                                    {{ paymenttype.payment_type }}
                                </a>
                            </td>
                            <td>{{ paymenttype.frequency|lower|capfirst }}</td>
                            <td>{{ paymenttype.min_amount }}</td>

                                {% if paymenttype.is_active %}
                                   <td title="Active savings account"> <i class="fa fa-check-square text-success fa-lg"></i></td>
                                {% else %}
                                    <td title="Inactive savings account"><i class="fa fa fa-exclamation-triangle fa-lg"></i></td>
                                {% endif %}
                            <td>
                                <a href="{% url 'payments:delete-type' pk=paymenttype.pk %}" class="btn btn-danger fa-lg">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>

                        </tr>
                      {% endfor %}
                      </tbody>
                  </table>
              </div>

          {% else %}
              <div>
                <h5>
                    No payment categories exist yet
                    <a href="{% url 'payments:make-payment-type' %}" class="btn btn-info">
                        add new
                    </a>
                </h5>
              </div>
          {% endif %}
      </div>
    <div class="card-footer">
        <nav aria-label="Members pagination">
            <ul class="pagination pagination-centered">
                {% if paymenttype_list.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link"><<</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ paymenttype_list.previous_page_number }}" class="page-link"><</a>
                    </li>
                {% endif %}

                {% for i in paymenttype_list.paginator.page_range %}
                    <li {% if paymenttype_list.number == i %} class="page-item active" {% endif %}>
                        <a href="?page={{i}}" class="page-link">{{i}}<span class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}

                {% if paymenttype_list.has_next %}
                    <li class="page-item">
                        <a href="?page={{ paymenttype_list.next_page_number }}" class="page-link">></a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ paymenttype_list.paginator.num_pages }}" class="page-link">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    </div>
    </div>
{% endblock page_content %}

templates/payments/make-payment.html
{% extends 'members/auth_base.html' %}
{% load static %}
{% block page_title %}Make Payment {% endblock page_title %}

{% block page_content %}

    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-6 col-8 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'payments:list-types' %}">Payments</a></li>
                    <li class="breadcrumb-item">Make payment</li>
                </ol>
            </div>
        </div>
        {% include 'messages.html' %}
        <div class="row">
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header text-center">
                            <h3 class="card-title pt-2">Make Payment for {{ member.get_full_name }}</h3>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'payments:make-payment' pk=member.pk %}" class="pt-3">{% csrf_token %}
                                {{ form.as_p }}
                                <div class="text-right">
                                    <button class="btn btn-info" type="submit">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xlg-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="card-header text-center">
                            <h3 class="card-title pt-2">Upload Excel Sheet</h3>
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'payments:upload-contributions' %}" enctype="multipart/form-data" class="pt-3">{% csrf_token %}
                                {{ upload_form }}
                                <div class="text-right mt-4">
                                    <button class="btn btn-info" type="submit">Upload</button>
                                </div>
                            </form>
                            <p>
                            <h3>Instructions</h3>
                              <ol>
                                  <li>Download sample excel file <a href="/static/downloads/contributions.xlsx">here</a></li>
                                  <li>Fill in payment details carefully!</li>
                                  <li>Double check to ensure member numbers correspond to actual members or contribution will be credited to wrong member.</li>
                                  <li>Upload payments for each category separately to reduce risk of erros.</li>
                              </ol>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}