fines/urls.py
from django.urls import path
from . import views


app_name = 'fines'

urlpatterns = [

    path('create-fine/<int:pk>', views.CreateFine.as_view(), name='create-fine'),
    path('pay-fine/<int:pk>', views.PayFine.as_view(), name='pay-fine'),
    path('list-fines/', views.ListFines.as_view(), name='list-fines'),
    path('update-fine/<int:pk>', views.UpdateFine.as_view(), name='update-fine'),
    path('list-member-fines/<int:pk>', views.ListMemberFines.as_view(), name='list-member-fines'),
]

loans/urls.py
from django.urls import path
from loans import views

app_name = 'loans'

urlpatterns = [
    path('', views.ListLoans.as_view(), name='loans'),
    path('view-disbursed-loan/<int:pk>/', views.ViewDisbursedLoan.as_view(), name='view-disbursed-loan'),
    path('armotization-schedule-website/', views.ViewArmotizedScheduleWebsite.as_view(), name='armotization-schedule-website'),
    path('armotization-schedule/', views.ViewArmotizedSchedule.as_view(), name='armotization-schedule'),
    path('disburse-loan/<int:request_id>/', views.DisburseLoan.as_view(), name='disburse-loan'),
    path('approve-loan/<int:pk>/', views.ApproveLoan.as_view(), name='approve-loan'),
    path('list-applications/', views.ListApplications.as_view(), name='list-applications'),
    path('list-disbursements/', views.ListDisbursements.as_view(), name='list-disbursements'),
    path('apply-loan/', views.ApplyLoan.as_view(), name='apply-loan'),
    path('delete/<int:pk>/', views.DeleteLoan.as_view(), name='delete'),
    path('update/<int:pk>/', views.UpdateLoan.as_view(), name='update'),
    path('list', views.ListLoans.as_view(), name='list-loans'),
    path('create-loan/', views.CreateLoanType.as_view(), name='create-loan'),
    path('loan-status/<int:pk>/', views.ShowLoanStatus.as_view(), name='loan-status'),
    path('print-repayment-statement/<int:pk>/', views.PrintRepaymentStatement.as_view(), name='print-repayment-statement'),
    path('print-loan-status/<int:pk>/', views.PrintLoanStatus.as_view(), name='print-loan-status'),
    path('repay-loan/<int:pk>/', views.RepayLoan.as_view(), name='repay-loan'),
    path('request-guarantor/<int:pk>', views.RequestGuarantor.as_view(), name='request-guarantor'),
    path('search-guarantor/<int:pk>', views.SearchGuarantor.as_view(), name='search-guarantor', ),
    path('approve-guarantee-request/<int:pk>', views.ApproveGuaranteeRequest.as_view(), name='approve-guarantee-request', ),
    path('list-guarantee-requests/', views.ListGuaranteeRequests.as_view(), name='list-guarantee-requests', ),
]

members/urls.py
from django.urls import path
from members import views

app_name = 'members'

urlpatterns = [
    path('welcome', views.Welcome.as_view(), name='welcome'),
    path('create-member', views.CreateMember.as_view(), name='create-member'),
    path('admin-create-member', views.AdminCreateMember.as_view(), name='admin-create-member'),
    path('bulk-upload-members', views.BulkMemberUpload.as_view(), name='bulk-upload-members'),
    path('directory', views.MemberDirectory.as_view(), name='directory'),
    path('login', views.Login.as_view(), name='login',),
    path('logout', views.Logout.as_view(), name='logout',),
    path('profile/<int:pk>/', views.MemberProfile.as_view(), name='profile', ),
    path('request-password-reset/', views.RequestPasswordReset.as_view(), name='request-password-reset'),
    path('reset-requested-password/', views.ResetRequestedPassword.as_view(), name='reset-requested-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions', ),
    path('edit-bank-account/<int:account_id>/', views.EditBankAccount.as_view(), name='edit-bank-account', ),
    path('create-bank-account/<int:member_id>/', views.CreateBankAccount.as_view(), name='create-bank-account', ),
    path('edit-member/<int:pk>/', views.EditMember.as_view(), name='edit-member', ),
    path('activate-account/<int:pk>/', views.ActivateAccount.as_view(), name='activate-account', ),
    path('create-password/<int:pk>/', views.CreatePassword.as_view(), name='create-password', ),
    path('change-password/', views.ChangePassword.as_view(), name='change-password', ),
    path('deactivate-account/<int:pk>/', views.DeactivateAccount.as_view(), name='deactivate-account', ),
    path('upload-profile-photo/<int:pk>/', views.UploadProfilePhoto.as_view(), name='upload-profile-photo', ),
    path('print-members-list', views.PrintMembersList.as_view(), name='print-members-list'),
    path('filter-members-list', views.FilterMembersList.as_view(), name='filter-members-list'),
    path('upload-scanned-id/<int:pk>', views.UploadScannedID.as_view(), name='upload-scanned-id'),
    path('', views.MemberDirectory.as_view(), ),
]

opensacco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', home_view.LoadHome.as_view(), name='home'),
    path('send-contact-message', home_view.SendContactMessage.as_view(), name='send-contact-message'),
    path('fines/', include('fines.urls'), name='fines'),
    path('accounting/', include('accounting.urls', namespace='accounting'), name='accounting'),
    path('downloads/', home_view.ViewDownloads.as_view(), name='downloads'),
    path('faqs/', home_view.ViewFAQS.as_view(), name='faqs'),
    path('members/', include('members.urls', namespace='members'), name='members'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('loans/', include('loans.urls', namespace='loans'), name='loans'),
    path('pettycash/', include('pettycash.urls', namespace='pettycash'), name='pettycash'),
    path('dividends/', include('dividends.urls', namespace='dividends'), name='dividends'),
    path('notifications/', include('notifications.urls', namespace='notifications'), name='notifications'),
    path('shares/', include('shares.urls', namespace='shares'), name='shares-home'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from payments import views


app_name = 'payments'

urlpatterns = [
    path('statement/<int:pk>', views.Statement.as_view(), name='statement'),
    path('make-payment-type/', views.MakePaymentType.as_view(), name='make-payment-type'),
    path('upload-contributions/', views.UploadContributions.as_view(), name='upload-contributions'),
    path('list-payments/', views.ListAllPayments.as_view(), name='list-payments'),
    path('make-payment/<int:pk>/', views.MakePayment.as_view(), name='make-payment'),
    path('update-payment/<int:pk>/', views.UpdatePayment.as_view(), name='update-payment'),
    path('list-types/', views.ListPaymentTypes.as_view(), name='list-types'),
    path('update-type/<int:pk>/', views.UpdatePaymentType.as_view(), name='update-type'),
    path('delete-type/<int:pk>/', views.DeletePaymentType.as_view(), name='delete-type'),
    path('print-contributions/', views.PrintContributions.as_view(), name='print-contributions'),
    path('print-statememt/<int:pk>', views.PrintStatement.as_view(), name='print-statement'),
    path('', views.ListPaymentTypes.as_view(), ),
]

loans/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from members.models import Member
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
import datetime

first_due_date = datetime.datetime.today() + datetime.timedelta(days=45)
# first_due_default = curr_date.replace(day=1)  # set date to 1st of the month when interest is calculated


class Loan(models.Model):
    name = models.CharField(max_length=150, blank=False, unique=True)
    min_amount = models.FloatField(verbose_name=_('Minimum amount'), blank=False)
    max_amount = models.FloatField(verbose_name=_('Maximum amount'), blank=False)
    repayment_period = models.IntegerField(
        verbose_name=_('Repayment period'),
        blank=True,
        help_text=_('Enter repayment period for this type of loan')
    )
    repayment_period_unit = models.CharField(
        verbose_name=_('Repayment period unit'),
        choices=(('WEEKS', 'Weeks'), ('MONTHS', 'Months')),
        default='MONTHS',
        max_length=50
    )
    interest_rate = models.FloatField(
        verbose_name='Interest rate (p.a.)',
        blank=False,
        max_length=50,
        default=12.0,
    )

    description = models.TextField(verbose_name=_('Description'), blank=True)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name=_('Date created'))

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("view_loans", "Can see loans"),
            ("request_loan", "Can request loan"),
        )


class LoanRequest(models.Model):
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Requesting member'),
        on_delete=models.DO_NOTHING
    )
    loan = models.ForeignKey(Loan, verbose_name=_('Loan type'), on_delete=models.DO_NOTHING,)
    amount_requested = models.FloatField(verbose_name=_('Amount requested'), blank=False)
    date_requested = models.DateTimeField(auto_now_add=True, verbose_name=_('Date requested'), blank=False,)
    details = models.TextField(
        verbose_name=_('More details'),
        blank=True,
        help_text=_('Provide any additional information here'),
    )
    status = models.CharField(
        max_length=100,
        choices=(('pending', _('Pending')), ('approved', _('Approve')), ('rejected', _('Reject')),),
        default='pending'
    )

    def disbursement(self):

        if self.is_disbursed():
            disbursement = Disbursement.objects.get(loan_request_id=self.pk)
        else:
            disbursement = None

        return disbursement

    def guarantors(self):

        """List of members who have been requested to guarantee loan request"""

        return Guarantor.objects.filter(
            loan_request=self.pk
        )

    def is_disbursed(self,):

        try:
            loan_request = Disbursement.objects.filter(loan_request_id=self.pk)
        except ObjectDoesNotExist:
            loan_request = None

        if loan_request.count() > 0:

            return True
        else:
            return False

    def first_due(self,):
        """Returns first_due date for repayment and calculating interests or
        'not disbursed' for pending and rejected loans"""
        try:
            disbursement = Disbursement.objects.get(
                loan_request_id=self.id
            )
            first_due = str(disbursement.first_due.strftime('%Y-%m-%d'))

        except ObjectDoesNotExist:
            first_due = 'not disbursed'

        return first_due

    def next_due(self,):
        """Returns next_due date for repayment and calculating interests or
        the value of first_due() if is not being repaid"""

        repayment = LoanRepayment.objects.filter(
            loan_request_id=self.id
        ).last()

        if repayment is not None:
            next_due = str(repayment.next_due.strftime('%Y-%m-%d'))
        else:
            next_due = self.first_due()

        return next_due

    def is_being_repaid(self,):
        """Returns true or false depending on whether the loan request is being repaid or not"""

        try:
            repayments = LoanRepayment.objects.filter(
                loan_request_id=self.id
            ).count()
        except ObjectDoesNotExist:
            repayments = 0

        if repayments > 0:
            return True
        else:
            return False

    def get_amount_outstanding(self,):
        """Returns the amount outstanding for the particular loan request"""

        if self.is_being_repaid():

            # get amount outstanding
            repayments = LoanRepayment.objects.filter(
                loan_request_id=self.id
            ).last()

            return repayments.outstanding

        else:  # loan is not being repaid, return amount disbursed

            try:
                disbursement = Disbursement.objects.get(
                    amount_disbursed__gt=0,
                    loan_request_id=self.id
                )
                amount_disbursed = disbursement.amount_disbursed

            except ObjectDoesNotExist:  # loan_request_id is not disbursed

                amount_disbursed = 0

            return amount_disbursed

    def get_total_repaid(self):
        """Returns the total amount repaid for the particular loan request."""

        try:
            repayments = LoanRepayment.objects.filter(
                loan_request_id=self.pk
            ).last()

            if repayments is None:  # No repayments yet

                total_repaid = 0

            else:
                total_repaid = repayments.total_paid

        except ObjectDoesNotExist:

            total_repaid = 0

        return total_repaid

    def __str__(self):
        return str(self.loan.name) + ' : ' + str(self.amount_requested)

    class Meta:
        permissions = (
            ("can_manage_loans", "Can manage loans"),
            ("view_requests", "Can see requests"),
        )


class Guarantor(models.Model):
    guarantor = models.ForeignKey(Member, on_delete=models.CASCADE,)
    amount = models.FloatField(max_length=20,)
    loan_request = models.ForeignKey(LoanRequest, on_delete=models.CASCADE)
    status = models.CharField(
        verbose_name=_('Status'),
        choices=(('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')),
        default='pending',
        max_length=50
    )
    response_message = models.TextField(max_length=5000, blank=True)

    def __str__(self):

        return self.guarantor.get_full_name()


class Disbursement(models.Model):
    loan_request = models.OneToOneField(
        LoanRequest,
        unique=True,
        on_delete=models.CASCADE,
        verbose_name=_('Loan request'),
    )
    amount_disbursed = models.FloatField(
        verbose_name=_('Amount disbursed')
    )
    repayment_period_unit = models.CharField(
        verbose_name=_('Repayment period unit'),
        choices=(('months', 'Months'), ('years', 'Years'), ('weeks', 'Weeks'), ('days', 'Days')),
        default='months',
        max_length=50
    )
    interest_rate = models.FloatField(
        verbose_name='Interest rate (p.a.)',
        blank=False,
        max_length=50,
        default=12.0,
    )
    interest_on = models.CharField(
        choices=(
            ('reducing_balance', _('Reducing balance')),
            ('flat_rate', _('Flat rate')),
        ),
        default='reducing_balance',
        max_length=50,
        verbose_name=_('Calculate interest on'),
    )
    repayment_period = models.IntegerField(
        verbose_name=_('Repayment period'),
        blank=True,
        help_text=_('Enter repayment period for this type of loan'),
        default=24
    )
    processing_fee = models.FloatField(
        verbose_name=_('Processing fee'),
        null=True
    )
    date_disbursed = models.DateTimeField(verbose_name=_('Date disbursed'), blank=False, auto_now_add=True)
    first_due = models.DateField(verbose_name=_('Date due'), blank=False, default=first_due_date)
    next_due = models.DateField(verbose_name=_('Next due'), blank=True, )

    def __str__(self):
        return str(self.amount_disbursed)

    class Meta:

        permissions = (
            ("disburse_loan", _("Can make loan disbursements")),
            ("view_loan_disbursements", _("Can see loan disbursements")),
        )

    def get_emi(self):

        disbursement = self

        # Skip fully repaid loans
        amount_outstanding = abs(disbursement.loan_request.get_amount_outstanding())

        if disbursement.repayment_period_unit == 'days':
            epochs = 365
        elif disbursement.repayment_period_unit == 'years':
            epochs = 1
        elif disbursement.repayment_period_unit == 'weeks':
            epochs = 52
        else:
            epochs = 12

        """calculate emi"""

        interest = (disbursement.interest_rate / epochs) / 100

        n = disbursement.repayment_period
        amount = disbursement.amount_disbursed

        if disbursement.interest_on == 'reducing_balance':
            num = ((1 + interest) ** n) - 1
            denm = interest * (1 + interest) ** n
            d = num / denm
            emi = amount / d
        else:  # use flat rate
            total = ((100 + (disbursement.interest_rate * disbursement.repayment_period / epochs)) / 100) * disbursement.amount_disbursed

            emi = total / disbursement.repayment_period

        return emi


class LoanRepayment(models.Model):
    """In future, rename to loan statement"""
    loan_request = models.ForeignKey(
        LoanRequest,
        verbose_name=_('Loan request'),
        on_delete=models.DO_NOTHING,
    )
    payment_date = models.DateTimeField(
        verbose_name=_('Payment date'),
        max_length=100,
        auto_now_add=True
    )
    next_due = models.DateTimeField(
        verbose_name=_('Next due'),
        max_length=100,
        null=True
    )

templates/loans/approve-loan.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Approve Loan Applications {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}
    <div class="card mb-0" id="directory">
      <div class="card-header">
        <h2 class="">Approve Loan Application</h2>
      </div>

    <div class="card-body p-2">
        {% if loan %}
        <div class="row">
            <div class="col-md-6">
                <table class="table table-responsive table-striped">
                    <tr>
                        <td class="text-info">Requested by</td>
                        <td>: <a href="{% url 'members:profile' pk=loan.requested_by_id %}"> {{ loan.requested_by.get_full_name }}</a></td>
                    </tr>
                    <tr><td class="text-info">Date Requested</td><td>: {{ loan.date_requested|date:'d-M-Y H:i:s' }}</td></tr>
                    <tr><td class="text-info">Amount Requested </td><td>: KES {{ loan.amount_requested }}</td></tr>
                    <tr><td class="text-info">Type of loan </td><td>: {{ loan.loan.name }}</td></tr>
                    <tr><td class="text-info">Status </td>
                        {% if loan.status == 'pending' %}
                            <td class="text-info">: {{ loan.status.title }} <i class="fa fa-exclamation-triangle"> &nbsp; </i></td>
                        {% elif loan.status == 'approved' %}
                            <td style="background: #5cb85c;">: {{ loan.status.title }}
                                &nbsp; <i class="fa fa-arrow-circle-o-right">&nbsp;</i>
                            <a class="btn btn-info" href="{% url 'loans:disburse-loan' request_id=loan.id %}">disburse</a>
                            </td>
                        {% elif loan.status == 'disbursed' %}
                            <td style="background: #5cb85c;">: {{ loan.status.title }}
                                <i class="fa fa-"> &nbsp; </i>
                            </td>
                        {% else %}
                            <td style="background: #d9534f;">: {{ loan.status.title }}  <span class="glyphicon glyphicon-remove-sign"> &nbsp; </span></td>
                        {% endif %}
                    </tr>
                    <tr><td class="text-info">Member number </td><td>: {{ loan.requested_by.member_number }}</td></tr>
                    <tr><td class="text-info">Member since </td><td>: {{ loan.requested_by.date_joined|date:'d-M-Y' }}</td></tr>
                    <tr><td class="text-info">Call </td><td>: {{ loan.requested_by.phone_number }}</td></tr>
                </table>
                <a href="{% url 'loans:loan-status' pk=loan.requested_by.pk %}" class="btn btn-info" role="button">View Loan Status</a>

            </div>
        <div class="col-md-6">
            <h3>Guarantors</h3><hr>
            {% if loan.guarantors|length > 0 %}
                <table class="table table-striped">
                    <thead>
                        <th>Name</th><th>Member #</th><th>Amount</th><th>Status</th>
                    </thead>
                    <tbody>
                        {% for guarantor in loan.guarantors %}
                            <tr>
                                <td>{{ guarantor.guarantor.get_full_name }}</td>
                                <td>{{ guarantor.guarantor.member_number }}</td>
                                <td>{{ guarantor.amount }}</td>
                                <td>{{ guarantor.status|capfirst }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            {% else %}
                <div class="alert alert-info">
                    No guarantors requested for this loan
                </div>
            {% endif %}

            <h3>Loan Status</h3>
            {% if not loan.status == "disbursed" %}
                <form class="" method="post" action="{% url 'loans:approve-loan' pk=loan.pk %}">{% csrf_token %}
                    <p>{{ form.status }}</p>
                    <p class="text-right">
                        <button class="btn btn-info btn-group-justified" type="submit">
                            Update <i class="fa fa-send"></i>
                        </button>
                    </p>
                </form>
            {% else %}
                <p>
                    Approved and disbursed, <a href="{% url 'loans:loan-status' pk=loan.requested_by.pk %}"> view status </a>
                </p>
            {% endif %}
        </div>
        </div>
    {% else %}
        <div class="alert alert-info">No loan application with that id was found.  </div>
    {% endif %}
    </div>

    </div>
{% endblock page_content %}

templates/loans/list.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Loan Products {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}
    <div class="card mb-0" id="directory">
      <div class="card-header">
        <h2 class="">Loan Products</h2>
      </div>

    <div class="card-body" style="padding: .5rem;">

          {% if loans|length > 0 %}

              <div class="table-responsive table-dark table-hover">
                  <table class="table table-striped">
                      <thead style="font-weight: 900;">
                        <tr>
                            <th>Code</th><th>Loan</th><th>Interest</th><th>Repayment</th>
                            <th style="text-align: right;">Min. Amount</th>
                            <th style="text-align: right;">Max. Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for loan in loans %}
                          <tr>
                            <td>{{ loan.pk }}</td>
                            <td>
                                <a href="{% url 'loans:update' pk=loan.pk %}">
                                    {{ loan.name }}
                                </a>
                            </td>
                              <td>{{ loan.interest_rate }}</td>
                              <td>{{ loan.repayment_period }} {{ loan.repayment_period_unit|lower|capfirst }}</td>
                              <td style="text-align: right;">{{ loan.min_amount }}</td>
                              <td style="text-align: right;">{{ loan.max_amount }}</td>
                          <td>
                              {% if perms.loans.delete_loan %}
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#delete-loan-{{ loan.pk }}"> delete </a>
                                <div id="delete-loan-{{ loan.pk }}" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4>Delete Loan {{ loan.name }} </h4>
                                            </div>
                                            <div class="modal-body">
                                                <h3 class="text-danger">Are you sure you want to delete {{ loan.name }} ?</h3>
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{% url 'loans:delete' pk=loan.pk %}" method="post" >
                                                    {% csrf_token %}
                                                    <button class="btn btn-danger" type="submit"> Delete </button>
                                                    <button class="btn btn-default" type="button" data-dismiss="modal"> Cancel </button>
                                                </form>
                                            </div>
                                        </div><!-- .modal-content -->
                                    </div>
                                </div>
                              {% endif %}
                        </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                  </table>
              </div>

          {% else %}
              <div>
                <h5>
                    No loan products exist yet,
                    <a href="{% url 'loans:create-loan' %}" class="">add new</a>
                </h5>
              </div>
          {% endif %}
      </div>
    <div class="card-footer">
        <nav aria-label="Loans pagination">
            <ul class="pagination pagination-centered">
                {% if loans.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link"><<</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ loans.previous_page_number }}" class="page-link"><</a>
                    </li>
                {% endif %}

                {% for i in loans.paginator.page_range %}
                    <li {% if loans.number == i %} class="page-item active" {% endif %}>
                        <a href="?page={{i}}" class="page-link">{{i}}<span class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}

                {% if loans.has_next %}
                    <li class="page-item">
                        <a href="?page={{ loans.next_page_number }}" class="page-link">></a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ loans.paginator.num_pages }}" class="page-link">>></a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    </div>
    </div>
{% endblock page_content %}

templates/loans/repay_loan.html
{% extends 'members/auth_base.html' %}
{% block page_title %}Loan Repayment {% endblock page_title %}
{% block page_content %}
    {% include 'messages.html' %}
    <div class="card mb-0" id="directory">
        <div class="card-header">
            <h2 class="">Make Loan Repayment</h2>
        </div>
    <div class="card-body p-2">
        <div class="row">
            <div class="col-5">
                <form method="post" action="{% url 'loans:repay-loan' pk=loan_request.pk %}">{% csrf_token %}
                    <table class="table table-responsive table-striped" style="max-width: 400px;">
                        <tr>
                            <td>
                                {{ form.loan_request.label }}
                                {{ field.loan_request.errors }}
                            </td>
                            <td>{{ form.loan_request }}</td>
                        </tr>
                        <tr>
                            <td>
                                Amount due (credit)
                                {{ field.credit.errors }}
                            </td>
                            <td>{{ form.credit }}</td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                <a class="btn btn-info btn" href="{% url 'loans:loan-status' pk=loan_request.requested_by_id %}">
                                    Loan Status <i class="fa fa-dollar"></i>
                                </a>
                            </td>
                            <td colspan="2" class="text-right">
                                <button class="btn btn-info btn" type="submit" name="submit">
                                    Submit <i class="fa fa-send"></i>
                                </button>
                            </td>
                        </tr>
                    </table>
                </form>
                <a href="{% url 'loans:armotization-schedule' %}?loan_request_id={{ loan_request.pk }}" class="btn btn-info btn-block">View Amortized Schedule</a>
            </div>
            <div class="col-7">
                <h3>Loan Summary</h3><hr>

                {% if loan_request %}
                    <table class="table table-responsive table-striped">
                        <thead>
                            <th>Loan </th>
                            <th style="text-align: right;">Amount</th>
                            <th style="text-align: right;">Balance</th>
                            <th style="text-align: right;">Interest</th>
                            <th style="text-align: right;" title="Equated Monthly Intallment">EMI</th>
                        </thead>
                        <tr>
                            <td>{{ loan_request.loan.name }}</td>
                            <td id="fixedAmount" style="text-align: right;">
                                {{ loan_request.amount_requested|floatformat:2 }}
                            </td>
                            <td style="text-align: right;">
                                {{ loan_request.get_amount_outstanding|floatformat:2 }}
                            </td>
                            <td style="text-align: right;">
                                {{ loan_request.loan.interest_rate }}% p.a
                            </td>
                            <td style="text-align: right;">
                                {{ emi|floatformat:2 }}
                            </td>
                        </tr>
                    </table>
                {% endif %}

            </div>
        </div>
    </div>
    <div class="card-footer">

    </div>
    </div>
{% endblock page_content %}